apiVersion: v1
kind: Secret
metadata:
  name: secret-guardian-api-secret
  labels:
    app: secret-guardian-api
type: Opaque
data:
  API_KEY: RVNUQSBFUyBVTkEgQVBJIEtFWSBTRUNSRVRB
  PRIVATE_KEY: RVNUQSBFUyBVTkEgQ0xBVkUgUFJJVkFEQQ==