apiVersion: v1
kind: Service
metadata:
  name: guardian-api-service
  labels:
    app: secret-guardian
    component: api
spec:
  type: NodePort
  selector:
    app: secret-guardian
    component: api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: secret-scanner-service
  labels:
    app: secret-guardian
    component: scanner
spec:
  type: NodePort
  selector:
    app: secret-guardian
    component: scanner
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30001
    protocol: TCP
    name: http
