name: secrets-scan
on: [push, pull_request]
jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar proyecto python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Escanear secretos con secret_guardian.py
        run: |
          python3 ./scripts/secret_guardian.py .
